[package]
name = "material_designer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.5.0", features = [] }

bevy_asset_ron = "0.2"
ron = { version = "0.7", features = ["indexmap"] }

indexmap = { version = "1.7", features = ["serde"] }
lazy_static = "1.4.0"
serde = "1"
